### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ruthetum** [ruthetum/study#52]
## SW
- [ ] kafka
- [ ] kubernetes
- [ ] istio
- [ ] localstack
- [ ] spring webflux
- [ ] axon framework
- [ ] go gin rest template

## Book
- [ ] 실전 카프카 개발부터 운영까지
- [ ] 데이터 중심 애플리케이션 설계
- [ ] gRPC 시작에서 운영까지

## Etc.
- [ ] skaffold
- [ ] armeria
- [ ] thrift
- [ ] spring batch
- [ ] jasypt

**Comment by ruthetum** [comment]
duplicated of #29
duplicated of #20

**Comment by ruthetum** [comment]
istio traffic management
- https://istio.io/latest/docs/concepts/traffic-management/
- https://bcho.tistory.com/1367

**Comment by ruthetum** [comment]
Ref. spring + kotlin

1. OOP
- https://codingnuri.com/seven-virtues-of-good-object/
- https://www.youtube.com/watch?v=dJ5C4qRqAgA
- https://d2.naver.com/helloworld/9879422

2. TDD
- https://gyuwon.github.io/blog/2019/03/03/tdd-is-not-a-design-methodology.html
- https://mjspring.medium.com/%EB%B2%88%EC%97%AD-tdd-%EB%B3%80%EC%A0%88%EC%9E%90-tdd%EB%8A%94-%EC%84%A4%EA%B3%84-%EA%B8%B0%EB%B2%95%EC%9D%B4-%EC%95%84%EB%8B%88%EB%8B%A4-2519b05474d0
- https://martinfowler.com/articles/is-tdd-dead/
- https://www.youtube.com/watch?v=PqA6zbhBVZc
- https://www.youtube.com/watch?v=D_tWlb2deX8

3. kopring
- https://www.youtube.com/watch?v=ewBri47JWII
